version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123123123
      POSTGRES_USER: karrot_user
      POSTGRES_DB: karrot
    ports:
      - "5555:5432"
