app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2
      enabled: true
