tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
tokenExpirationMsec: 864000000

springdoc:
  api-docs:
    path: /swagger-ui.html
spring:
  datasource:
    generate-unique-name: false
    username: karrot_user
    password: 123123123
    url: jdbc:postgresql://127.0.0.1:5555/karrot
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 80
