package me.min.karrotmarket.item;

public enum Category {
    DIGITAL_DEVICE,
    HOME_APPLICATION,
    FURNITURE_INTERIOR,
    INFANT_CHILD,
    LIVING_PROCESSED_FOOD,
    CHILD_BOOK,
    WOMAN_CLOTHING,
    MAN_CLOTHING,
    GAME_HOBBY,
    BEAUTY,
    PET,
    BOOK_TICKET_RECORD,
    ETC_USED_GOODS,
    USED_CAR
}
